### ISSUE TITLE
Wrong error message "Min > Max"

### ISSUE THREAD

**Issue by maxela** [bartbutenaers/node-red-contrib-interval-length#12]
An interval-length node with Minimum = 4990 ms and Maximum = 15010 ms reports an error message "Min > Max" in the debug area when deployed, which is obviously wrong. At runtime the flow works just fine as expected.

![grafik](https://user-images.githubusercontent.com/4155400/158870601-301db858-706a-4f50-a9ec-0c048baf0c05.png)

With Minimum = 4990 ms and Maximum = 50 ms no error message is reported at deployment, but in this case the error message would be correct.

I assume this comes from a alpha-numerical comparison, but it should be a numerical comparison in interval-length.js line 139:

https://github.com/bartbutenaers/node-red-contrib-interval-length/blob/0bfb6bb7b92f674ef25ace1f30845eaa4a860955/interval_length.js#L139

This might solve the issue (untested):

`        if(this.minimum && this.maximum && Number(this.minimum) > Number(this.maximum)) {`

I run Node Red version 11.1.0 as addon in Home Assistant core-2022.3.5

**Comment by bartbutenaers** [comment]
Hi @maxela,

You are right that it is an alphanumerical comparison, because Node-RED sends strings for all config screen values (which are no TypedInputs).  It seemed to be only a problem for unit 'milliseconds', because then no conversion of the data is required.

It should be fixed now in the new version ***0.0.5***, which is available in the Node-RED pallette:

![image](https://user-images.githubusercontent.com/14224149/158907075-13670a53-6ccb-4c66-83d3-a86dddca5201.png)

Please close this issue when everything is solved for you!

Bart

**Comment by maxela** [comment]
Great, thanks for your quick reaction, @bartbutenaers! The fix looks good - better than what I suggested ;)
I have to wait for the change to be available in an update for the HA Node-RED addon. I'll give you feedback and close the issue asap then. But I expect the change to fix the issue.

**Comment by maxela** [comment]
I just upgraded to node-red version 11.1.1 and tested with success. Thanks @bartbutenaers !
