### ISSUE TITLE
on timeout send a timeout message

### ISSUE THREAD

**Issue by MatzeJoerling** [bartbutenaers/node-red-contrib-interval-length#2]
Hi,

have used the node for my rainmeter. It gives a toggle every 5ml. I measure the time between 2 toggles to get the ml per hour. but if it rains 3ml and then stops i need a timeout that sends a "stopped raining" message.
You have a timeout in your node, but is should send a message at timeout.
at the moment i have a timeout node.  What is OK, because a node should do not to much...
I know there is a "window timeout", but that is only for the window function.

![screenshot 2017-11-26 16 12 49](https://user-images.githubusercontent.com/25864208/33241399-f37be70a-d2c4-11e7-8f88-3bf378608647.png)

But if you consider adding the timeout message it would be a nice feature.

regards M.

**Comment by bartbutenaers** [comment]
Hello Matze,

That is indeed something I should have added already in the first version.

I also agree that a node shouldn't do to much.  But on the other hand I'm not a big fan of very complex flows.  And since this node is measuring time intervals, it is rather obvious that it is able to notify you when that time interval becomes too large.

Moreover, it was a very _small change_ to implement:

![image](https://user-images.githubusercontent.com/14224149/33291918-c365b6aa-d3c7-11e7-9341-b49a5f677525.png)

1. You can specify a timeout interval
2. The existing checkbox text has been updated a bit to indicate that it is about generating a 0-interval message, instead of a real timeout message
3. A new checkbox has been added to select whether you want a single timeout message, or multiple timeout messages

The node help screen and the Github readme.md files have been updated to explain this new functionality.

Could you please test it and give me feedback.  I will publish it together with your other issue in version 0.0.2.

Kind regards,
Bart

**Comment by MatzeJoerling** [comment]
Hi Bart,

was not @home tha last 3 days, will check that on weekend.
thanks for your fast response.

regards M.

2017-11-27 23:12 GMT+01:00 bartbutenaers <notifications@github.com>:

**Comment by MatzeJoerling** [comment]
Hi Bart,

for me it is working.

regards Martin

2017-11-30 21:17 GMT+01:00 Martin Hierling <martin.hierling@gmail.com>:

**Comment by bartbutenaers** [comment]
Hello Matze,
version **0.0.2** has been published on NPM.
Kind regards,
Bart
