### ISSUE TITLE
Add a Time Since Last Message feature?

### ISSUE THREAD

**Issue by QuagmireMan** [bartbutenaers/node-red-contrib-interval-length#4]
Would you be able to add another output that could give you the time since the last message was received? For example when the timeout is triggered it will output on this new output the time since the last message arrived.

This would be very helpful in checking lots of sensors on my network.

**Comment by bartbutenaers** [comment]
Hey @QuagmireMan,

I did a quick test with a timeout of 1000 milliseconds:

![image](https://user-images.githubusercontent.com/14224149/47951725-ebc3c700-df64-11e8-9321-cde75f8fad54.png)

1. Message is injected
2. One second later a timeout message is generated

Normally the ```msg.payload``` of the output message should contain the time interval between the last message and now.  So in this example the payload should have been ```1000``` (milliseconds), since the last message has arrived 1 second ago.

But seems there is a **bug** in the code, because now you see an interval of ```0``` milliseconds.  If I fix that bug, I think that would be sufficient for your use case.  Is this correct, or have I misunderstood your question?

Kind regards,
Bart

**Comment by bartbutenaers** [comment]
Second question: do you think it would be usefull to have an extra field in the output message (on both outputs), that contains the **timestamp** when the _previous_ message has arrived.

Have created a test version Github that implements this feature.  If you want to experiment with it, you can install it directly from Github (since it is not published on NPM yet):
```
npm install bartbutenaers/node-red-contrib-interval-length
```
For example:

![image](https://user-images.githubusercontent.com/14224149/47951796-16fae600-df66-11e8-932d-31f4b1dc4a6e.png)

1. An input message A is generated (at timestamp 1541245184219)
2. A second input message B is generated (at timestamp 1541245191273)
3. An output message is generated which contains in the ```msg.payload``` the number of milliseconds between message B and the previous message A.
4. A **new field** ```msg.timestamp``` now contains the timestamp (1541245184229) at which message A has arrived in the interval node.  This timestamp is a little bit larger as the timestamp in point 1, since it takes Node-RED some time to pass the message between the nodes.

Or is this useless information.  Any suggestions are welcome !
Bart

**Comment by QuagmireMan** [comment]
> Hey @QuagmireMan,
> 
> I did a quick test with a timeout of 1000 milliseconds:
> 
> ![image](https://user-images.githubusercontent.com/14224149/47951725-ebc3c700-df64-11e8-9321-cde75f8fad54.png)
> 
> 1. Message is injected
> 2. One second later a timeout message is generated
> 
> Normally the `msg.payload` of the output message should contain the time interval between the last message and now. So in this example the payload should have been `1000` (milliseconds), since the last message has arrived 1 second ago.
> 
> But seems there is a **bug** in the code, because now you see an interval of `0` milliseconds. If I fix that bug, I think that would be sufficient for your use case. Is this correct, or have I misunderstood your question?
> 
> Kind regards,
> Bart

Having the 1000 in the payload is what I was looking for.  Also, when the "Repeat timeout msg periodically" checkbox is checked, would the next message be 2000 then 3000?  Having this value accumulate is the feature I am after.

Thank you so much for jumping on this  in such a short 'interval"! :smile:

**Comment by QuagmireMan** [comment]
> 4\. **new field** `msg.timestamp` now contains the timestamp (1541245184229) at which message A has arrived in the interval node.  This timestamp is a little bit larger as the timestamp in point 1, since it takes Node-RED some time to pass the message between the nodes.

As long as this isn't a performance hit I think this could be useful.

**Comment by bartbutenaers** [comment]
@QuagmireMan 

There is a new 0.0.3 version available on Github, which can be installed like this:
```
npm install bartbutenaers/node-red-contrib-interval-length
```
Would really appreciate if you could experiment with it, before I publish it on NPM.
- There is an `msg.timestamp` field in the output message which contains the timestamp of the previous message.  In the node config screen you can change the fieldname, e.g. to `msg.my_timestamp` .
- The msg.payload now contains also for timeout messages the time interval since the last message.  If you have selected to keep repeating timeout messages, you will see that the payload contains the ENTIRE time interval since the last message:

    ![image](https://user-images.githubusercontent.com/14224149/47965565-2bfc7580-e049-11e8-9478-d2c6c60c43cf.png)

   Remark: the values are not exactly 1000, 2000, 3000 ... (i.e. multiples of the 1000 which is the timeout period), because NodeJS will not exactly call the timeout timer after 1000...  
+ When a new message arrives in between, you will see that the timeouts start again counting from zero:

  ![image](https://user-images.githubusercontent.com/14224149/47965603-872e6800-e049-11e8-9498-e296d05d1eb5.png)

   Remark: the green arrows show that the msg.timestamp will be a bit later as the original timestamp (at which the messages are created), since the msg.timestamp is the timestamp at which the messages have arrived in our interval node ...
+ There is now also the possibility to reset the measurements, by sending an msg.reset to this node.

Hope to hear from you soon!
Bart

**Comment by QuagmireMan** [comment]
This is great! Exactly what I was looking for!

The only thing I see, which I do not think is a big deal, when you send a reset before the interval starts or 2 resets in a row you get a "TypeError: Cannot read property 'windowTimer' of undefined" message.  I would just consider this improper use of the node :smile: 

Great work!

**Comment by bartbutenaers** [comment]
Glad that I could help you.
Thanks for testing !!  
I have fixed the '_**undefined timer'**_ error and version 0.0.3 is now available in your palette via NPM:

![image](https://user-images.githubusercontent.com/14224149/48008555-39cdfb80-e11a-11e8-880b-b74d4225b820.png)

Have fun with your sensors...
